stages:
  - build
  - deploy

build_image:
  stage: build
  tags:
    - specific-hetzner
  only:
    - main
  script:
    - docker info
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - docker login -u gitlab-ci-token -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

deploy_prod:
  stage: deploy
  tags:
    - specific-hetzner
  only:
    - main
  script:
    # Create host directory if it doesn't exist
    # - mkdir -p /var/storage/mesto/static

    # restart web container #2
    - docker stop clubeeo_mesto_app_2 || true
    - docker container rm clubeeo_mesto_app_2 || true
    - docker run --name clubeeo_mesto_app_2 --env-file $PROD_ENV -d -p 127.0.0.1:9961:9900
      --env RUN_MIGRATIONS=true
      -v /var/storage/mesto/static/uploads:/app/static/uploads
      --restart unless-stopped $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      --add-host=host.docker.internal:host-gateway
    - sleep 12 # let first container restart
    
    # restart web container #1
    - docker stop clubeeo_mesto_app_1 || true
    - docker container rm clubeeo_mesto_app_1 || true
    - docker run --name clubeeo_mesto_app_1 --env=RUN_WORKER=true --env-file $PROD_ENV -d -p 127.0.0.1:9960:9900
      -v /var/storage/mesto/static/uploads:/app/static/uploads
      --restart unless-stopped $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      --add-host=host.docker.internal:host-gateway

    # stop temporary container
    - docker stop clubeeo_mesto_app_2 || true
